include:
   - local: .gitlab/.gitlab-cloud-template.yml

validate:
    stage: validate
    script:
      - terraform validate

plan:
    stage: plan
    dependencies:
      - validate    
    script:
      - terraform plan

apply:
    stage: apply
    dependencies:
      - plan    
    script:
      - terraform apply
    only:
      refs:
        - merge_requests
        - master
    allow_failure: false